import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata = {
  title: "Wanderlust Travel Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={poppins.className}>
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
